# Generated by Django 3.0 on 2020-07-03 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20200703_1422'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
